language: go

sudo: false
env:
go:
  - 1.4

script:
  - GOBIN=$HOME; export GOBIN
  - go get
  - go get "github.com/0xfaded/eval"
  - go get "github.com/mgutz/ansi"
  - go get "github.com/rocky/go-fish/cmd"
  - go get "github.com/rocky/go-types"
  - go get "github.com/rocky/go-loader"
  - go build
  - go build make_env.go
  - go install make_env.go
  - $HOME/make_env > repl_imports.next && mv repl_imports.next repl_imports.go
# need to work on not running out of source tree
# - go test -v
