language: go

env:
go:
  - tip
  - 1.2

script:
  - GOBIN=$HOME; export GOBIN
  - go get
  - go build
  - go build make_env.go
  - go install make_env.go
  - $HOME/make_env > repl_imports.next && mv repl_imports.next repl_imports.go
# need to work on not running out of source tree
# - go test -v
